### ISSUE TITLE
[Help] 请问我怎么改变被``包裹的字体的颜色,还有就是菜单栏上方的颜色,谢谢

### ISSUE THREAD

**Issue by wang-xiaowu** [blleng/hexo-theme-lx#22]
If yuo meet some problems when using `lx`，*please make sure that you've read the [README](https://github.com/blleng/hexo-theme-lx/blob/master/README.md) and the comment in `_config.yml` carefully but didn't find solution*.

---

- [x] I have read the README and _config.yml but didn't find solution.

#### Description

Desciption:

Hexo version:

Lx version：
`latest`
More infomation(If needed):

**Comment by blleng** [comment]
未在主题配置文件中提供直接的修改途径，你可以自行修改css样式。

**Comment by wang-xiaowu** [comment]
> 未在主题配置文件中提供直接的修改途径，你可以自行修改css样式。

改完代码之后它又自动改回去了 没找到原因,方便解答下么

**Comment by blleng** [comment]
如果仅修改了source/css文件夹中的styl文件，lx加载的仍会是jadelivr CDN上的css文件，你需同时修改主题配置文件中的css_dir配置。

**Comment by wang-xiaowu** [comment]
请问下正确的配置路径是什么

![image](https://user-images.githubusercontent.com/44340137/156306452-990ec58c-0a95-4a8d-b6cb-0e2fddd3bc70.png)

**Comment by blleng** [comment]
css文件地址为 `/css/main.css`

---

也可gulp压缩后使用`/dist/css/main.min.css`

**Comment by wang-xiaowu** [comment]
> /css/main.css

好的 谢谢

**Comment by wang-xiaowu** [comment]
> css文件地址为 `/css/main.css`
> 
> 也可gulp压缩后使用`/dist/css/main.min.css`

我无法通过custom.styl覆盖base.styl中变量么

**Comment by blleng** [comment]
> 我无法通过custom.styl覆盖base.styl中变量么

可以，`custom.styl`的优先级更高.
