### ISSUE TITLE
[HELP] 文章摘要

### ISSUE THREAD

**Issue by n-WN** [blleng/hexo-theme-lx#28]
If you want to report a bug，please make sure that the bug is caused by `lx` and you didn't do anything wrong.
###### 我没有主动操作相关问题的关键文件（但有可能不经意碰到了）
---

- [ √] I'm sure that the bug is not caused by myself and is related to `lx`.

#### Description

`lx` verison: 不止如何获取

`hexo` version: 6.1.0

Environment（OS,Browser,Nodejs version...）:Win11,安卓12，iOS13；chrome，edge，safari 都会如此

Description: 
#### 在执行完hexo g -d 后云端和本地访问均为英文菜单，过一会才会变为中文（或许不是lx的问题，我也不确定此条问题的原因，谢谢）

Sreenshot(If needed):
![image](https://user-images.githubusercontent.com/30841158/162569732-f3b450bb-6413-4824-a23d-617b9a1e4e58.png)

**Comment by blleng** [comment]
第一个问题：
请使用`<!--more-->`标签确定文章摘要长度。

第二个问题：
请清理浏览器缓存。

**Comment by blleng** [comment]
例如：
``` markdown example.md
title: ...
date: ...
...
---

This is a short description for the whole article.

<!--more-->

Article Content Here

```

于是， `<!--more-->`标签前的内容`This is a short description for the whole article.`成为文章摘要，在首页展示，而标签之后内容隐藏。

**Comment by n-WN** [comment]
谢谢，我对我的不专业向你道歉，这是我第一次使用hexo主题，还不太熟练，很感谢你的回复！

###### theme version: 0.4.3
