### ISSUE TITLE
[BUG] 作者你好, cdn应该是挂了

### ISSUE THREAD

**Issue by wang-xiaowu** [blleng/hexo-theme-lx#29]
If you want to report a bug，please make sure that the bug is caused by `lx` and you didn't do anything wrong.

---

- [x] I'm sure that the bug is not caused by myself and is related to `lx`.

#### Description

`lx` verison:
latest
`hexo` version:
latest
Environment（OS,Browser,Nodejs version...）:

Description:
作者你好, cdn应该是挂了, 挂链接你看下
[jqeury](https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js)

Sreenshot(If needed):
![image](https://user-images.githubusercontent.com/44340137/169639362-b7eae9bf-9166-441b-93b7-bc4e830ca253.png)
![image](https://user-images.githubusercontent.com/44340137/169639388-17f1b885-8737-4a2b-b8d9-304efd468458.png)

**Comment by blleng** [comment]
谢谢提醒，核心资源现已临时启用unpkg替换jsdelivr。

**Comment by wang-xiaowu** [comment]
> 时启用unpkg替换jsdelivr。

好的, 用户需要更新么?
我的博客现在也无法使用了

**Comment by blleng** [comment]
> > 时启用unpkg替换jsdelivr。
> 
> 好的, 用户需要更新么? 我的博客现在也无法使用了

在lx主题目录git pull一下就好，如果无法pull的话就将配置文件中所有"https://cdn.jsdelivr.net/npm"替换为"https://unpkg.com"

**Comment by wang-xiaowu** [comment]
ok
