### ISSUE TITLE
[Help] 如果我想自行在指定位置 （比如菜单栏 ）添加一段html代码 应该怎么操作呢

### ISSUE THREAD

**Issue by n-WN** [blleng/hexo-theme-lx#35]
If yuo meet some problems when using `lx`，*please make sure that you've read the [README](https://github.com/blleng/hexo-theme-lx/blob/master/README.md) and the comment in `_config.yml` carefully but didn't find solution*.

---

- [ √] I have read the README and _config.yml but didn't find solution.

#### Description

Desciption: 如果我想自行在指定位置 （比如菜单栏 ）添加一段html代码 应该怎么操作呢，找过了本地blog下的目录，没有找到可以提供更改的地方，（在next主题 下 通过 更改 .styl 文件内容 实现的页面html 添加 ）但在lx主题 我不知道该怎么做

Hexo version: 6.2.0

Lx version：0.4.3

More infomation(If needed):

**Comment by blleng** [comment]
您想要修改的内容在`layout`文件夹中

**Comment by n-WN** [comment]
谢谢



在 2022-08-31 18:46:48，"Leng" ***@***.***> 写道：

您想要修改的内容在layout文件夹中

**Comment by n-WN** [comment]
> 您想要修改的内容在 `layout`文件夹中

**Comment by n-WN** [comment]
> 您想要修改的内容在`layout`文件夹中

成功了 哈哈哈

**Comment by n-WN** [comment]
> 您想要修改的内容在`layout`文件夹中

成功了哈哈哈，欢迎参观
https://n-wn.github.io/
![图片](https://user-images.githubusercontent.com/30841158/187672430-4b1c9ea0-f8b2-4dbe-bebf-fb164bf9c861.png)

**Comment by blleng** [comment]
👍
