### ISSUE TITLE
[BUG] 页面超出显示范围

### ISSUE THREAD

**Issue by n-WN** [blleng/hexo-theme-lx#36]
If you want to report a bug，please make sure that the bug is caused by `lx` and you didn't do anything wrong.

---

- [√ ] I'm sure that the bug is not caused by myself and is related to `lx`.

#### Description

`lx` verison:  0.4.3

`hexo` version:  6.2.0

Environment（OS,Browser,Nodejs version...）: 火狐最新版 edge 安卓chrome 均会出现此问题（我设备上的所有浏览器

Description: 页面宽度小于一行长串字符长度时 就会挤出到屏幕外（体现是页面可以左右滑动
                    博客地址（供方便测试）：https://n-wn.github.io/2022/08/26/AirDrop%E4%B8%BB%E9%A2%98%E5%AF%86%E7%A0%81%E9%A2%98Wp/

Sreenshot(If needed): 

错误的展示形态
![图片](https://user-images.githubusercontent.com/30841158/187727946-bb76fd35-c1db-4ce0-a107-e80d11e1a19b.png)

---

正确的展示形态
![图片](https://user-images.githubusercontent.com/30841158/187728504-b3ef0c12-91a4-4b49-aad6-63efc59daadb.png)

**Comment by blleng** [comment]
好的，谢谢，我已经注意到了这个问题。
你可以在`lx/_config.yml`中将`custom_css`修改为`true`，在`lx/source/css/custom.styl`中添加以下内容以临时解决该问题：
```
.lx-post {
    word-wrap: break-word;
    word-break: break-all;
    overflow: hidden;
}
```

**Comment by blleng** [comment]
在`lx`文件夹下：
```
git pull
```
新版本已解决该问题。
