### ISSUE TITLE
[Help] Lack of documentation

### ISSUE THREAD

**Issue by dhaneshsivasamy07** [blleng/hexo-theme-lx#9]
If yuo meet some problems when using `lx`，*please make sure that you've read the [README](https://github.com/blleng/hexo-theme-lx/blob/master/README.md) and the comment in `_config.yml` carefully but didn't find solution*.

---

- [ x ] I have read the README and _config.yml but didn't find solution.

#### Description
- There is no documentation for adding the post images, help us with it clearly in the documentation
- The menu bar style is changed form `greenish` to `gol-b` and other colors all I get in the webpage is a blank grey background

**Comment by blleng** [comment]
For picture addition, please refer to the Markdown syntax.

**Comment by blleng** [comment]
To add a picture in the Markdown 
```markdown
![name_of_pic](url_of_pic)
```

**Comment by blleng** [comment]
I will check the problem on the menu bar in the further week.

**Comment by dhaneshsivasamy07** [comment]
> I will check the problem on the menu bar in the further week.

Thanks @blleng

**Comment by blleng** [comment]
I didn't find any problem about the menu bar. Could you give a link of your site?

**Comment by dhaneshsivasamy07** [comment]
The problem I faced while trying it locally so I didn't implement it on my site

**Comment by blleng** [comment]
Sorry, but I didn't find any problem.
